name: Build mc_rtc web demo

on:
  repository_dispatch:
    types:
    - build-master
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Compilation
      shell: bash
      run: |
        ./build.sh
        git clone -b gh-pages https://gergondet:${{ secrets.GH_PAGES_TOKEN }}@github.com/mc-rtc/demo /tmp/website
        cp artifacts/* /tmp/website/
        cd /tmp/website
        git add .
        git config --global user.email "pierre.gergondet@gmail.com"
        git config --global user.name "Pierre Gergondet (Automated CI update)"
        git commit -m "Automated update"
        git push origin gh-pages
