name: Build mc_rtc web demo

on:
  repository_dispatch:
    types:
    - build-master
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Compilation
      shell: bash
      run: |
        ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: demo
        path: artifacts/
